import os
API_ID = int(os.getenv("API_ID"))
API_HASH = os.getenv("API_HASH")
BOT_TOKEN = os.getenv("BOT_TOKEN")
START_MSG = os.getenv("START_MSG")
BOT_ADI = os.getenv("BOT_ADI")
PLAY_LIST = os.getenv("PLAY_LIST")
BTN_NAME = os.getenv("BTN_NAME")
BTN_URL = os.getenv("BTN_URL")
LIST_NAME = os.getenv("LIST_NAME")
LIST_URL = os.getenv("LIST_URL")
OWNER_HELP = os.getenv("OWNER_HELP")
HELP = os.getenv("HELP")
TELIMAT = os.getenv("TELIMAT")
PRIVACY_MSG = os.getenv("PRIVACY_MSG")
DATABASE_URL = os.getenv("DATABASE_URL")
DURATION_LIMIT = int(os.getenv("DURATION_LIMIT", "7"))
OWNER_ID = list({int(x) for x in os.environ.get("OWNER_ID", "").split()})
